CREATE TABLE asos_prop (
	Colors VARCHAR NOT NULL PRIMARY KEY,
	ASOS_US DECIMAL NOT NULL,
	ASOS_FR DECIMAL NOT NULL,
	ASOS_ES DECIMAL NOT NULL,
	ASOS_DE DECIMAL NOT NULL,
	ASOS_IT DECIMAL NOT NULL,
	ASOS_AU DECIMAL NOT NULL
);


CREATE TABLE mnytra_prop (
	Colors VARCHAR NOT NULL PRIMARY KEY,
	myntra_IN DECIMAL NOT NULL
);



